;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-paren
        complete-symbol
        ds/open-next-line
        ds/open-previous-line
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        indent-for-tab-command
        kill-region
        kill-sexp
        org-self-insert-command
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ))
