;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LilyPond-electric-close-paren
        backward-kill-sentence
        backward-sexp
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        complete-symbol
        dabbrev-expand
        default-indent-new-line
        delete-indentation
        ds/open-next-line
        ds/open-previous-line
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        forward-sexp
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        kill-sexp
        mark-sexp
        markdown-outdent-or-delete
        nxml-electric-slash
        org-end-of-line
        org-fill-paragraph
        org-self-insert-command
        sh-assignment
        slime-space
        transpose-words
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        ds/exwm-popup-shell
        end-of-buffer
        handle-switch-frame
        projectile-compile-project
        tts-editor/save-and-play
        xref-pop-marker-stack
        ))
