#!/usr/bin/env bash

externalIp="$(dig +short myip.opendns.com @resolver1.opendns.com)"

color="#dca3a3"

if [[ -z "$externalIp" ]] || [[ $(expr match "$externalIp" "[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}") -eq 0 ]]
then
    echo "<span color='$color'>0.0.0.0</span>"
    exit
fi



echo "<span color='$color'>$externalIp</span>"
