#!/usr/bin/env bash

vpn_name="$(systemctl list-units --plain --state=active | grep openvpn-client@ | awk '{print $1}' | sed -e 's/openvpn-client@//' -e 's/.service//')"

externalIp="$(dig +short myip.opendns.com @resolver1.opendns.com)"

color="#dca3a3"
lock=""

if [[ -z "$externalIp" ]] || [[ $(expr match "$externalIp" "[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}") -eq 0 ]]
then
    echo "<span color='$color'>0.0.0.0</span>"
    exit
fi


if [[ -n "$vpn_name" ]]
then
    color="#7f9f7f"
    lock=""
fi


echo "<span color='$color'>$externalIp $lock $vpn_name</span>"
