#!/usr/bin/env bash

declare -a tzs
tzs=( "GMT" "Asia/Hong_Kong" "US/Eastern" "Europe/Berlin" "Europe/Moscow")
action="$1"
if [[ -n "$action" ]]
then
    case "$action" in
        next) current=$[$(cat /tmp/$USER-worldclock) + 1];;
        previous) current=$[$(cat /tmp/$USER-worldclock) + 1];;
    esac
    [[ "$current" -lt 0 ]] && current=$[${#tzs[@]} - 1]
    [[ "$current" -ge "${#tzs[@]}" ]] && current=0
    echo $current > /tmp/$USER-worldclock
    exit
fi

while true
do
    current=$(cat /tmp/$USER-worldclock)
    [[ -z "$current" ]] || [[ "$current" -ge "${#tzs[@]}" ]] && current=0

    # echo "$current/${#tzs[@]} ${tzs[$current]}"
    # echo '(<span color="#dcdccc">'$(TZ=${tzs[$current]} date "+%Y.%m.%d %l:%M %P")'</span>' '<span color="#a9a999">'${tzs[$current]}'</span>)'
    echo '<span color="#a9a999">'$(TZ=${tzs[$current]} date "+%Y.%m.%d %H:%M")'</span> <span color="#dfaf8f">'$(echo ${tzs[$current]} | sed -r -e 's/([a-zA-Z]+)\/([a-zA-Z]+)/\1 - \2/' -e 's/_/ /')'</span> <span>'$(TZ=${tzs[$current]} date "+%z" | sed -r -e 's/([+-])([0-9][0-9]).*/\1\2h/' -e 's/([+-])0([0-9]h)/(\1\2)/' -e 's/\(.0h\)//')'</span>'

    sleep 1
done
