#!/usr/bin/env bash

UPSTRING="$(uptime -p)"

echo "<span color='#a9a999'>$UPSTRING</span>" | sed -r \
    -e 's/up//' \
    -e 's/ weeks?,?/w/' \
    -e 's/ days?,?/d/' \
    -e 's/ hours?,?/h/' \
    -e 's/ minutes?,?/m/' \
    -e 's/ seconds?,?/s/'
